configuration: Release
init:
  - git config --global core.autocrlf true
  # If there's a tag, use that as the version.
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq "true"){Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"}
build_script:
  - cmd: dotnet test test\Bazinga.AspNetCore.Authentication.Basic.Tests.csproj -c Release
after_build:
  - cmd: dotnet pack --no-build -c Release
on_success:
  - ps: .\coverage.ps1 -UploadCodecov
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
os: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
artifacts:
- path: '**\*.nupkg'
  name: bazinga-basic-auth-nuget-packages
deploy:
  release: $(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: ec+Solbkj/2PwO6fDaJYlHPLm9qMqx13xlO3byqtlKGOZcW3thTp5nXNwi6m3PwE
  artifact: /.*\.nupkg/
  draft: true
  on:
    appveyor_repo_tag: true